### ISSUE TITLE
Panics if input to `filter:` is not in UTF-8 encoding

### ISSUE THREAD

**Issue by Minoru** [newsboat/newsboat#1437]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**: r2.22.1-140-g31ae 

Config is empty.

Urls file:

```
filter:echo:http://localhost:8000
```

Note that `echo` simply prints out a newline and exits. There's no way this line can fail :)

Steps to reproduce the issue:

1. Put [response.txt](https://github.com/newsboat/newsboat/files/5821849/response.txt) somewhere. Note that the file is in ISO-8859-1 encoding.

2. In a terminal, start netcat server on port 8000. It will respond with the contents of response.txt to whoever connects first:

        $ cat response.txt | nc -l -p 8000

3. Start Newsboat and reload the feed.

4. Netcat won't close the connection automatically, so go back to the terminal and press ^C to kill netcat. That'll make Newsboa finish the reload — and crash.

**Other info you think is relevant**:
GDB backtrace:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fa6c1bc7537 in __GI_abort () at abort.c:79
#2  0x00007fa6c1e1b7ec in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fa6c1e26966 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fa6c1e269d1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fa6c1e26c65 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000559d98485fc7 in void rust::cxxbridge05::panic<std::invalid_argument>(char const*) ()
#7  0x0000559d98486016 in rust::cxxbridge05::Str::Str(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) [clone .cold] ()
#8  0x0000559d985bf056 in newsboat::utils::run_program (argv=0x7fff48a7fc98, argv@entry=0x7fff48a7fc80, 
    input="<rss version=\"2.0\">\n<channel>\n    <title>\300\301\302\303\304\305\306\307\310\311\312\313\314\315\316\317\320\321\322\323\324\325\326\327\330\331\332\333\334\335\336\337\340\341\342\343\344\345\346\347\350\351\352\353\354\355\356\357\360\361\362\363\364\365\366\367\370\371\372\373\374\375\376\377</title>\n    <link>http://noticias.uol.com.br/</link>\n    <description>timas Notias</descriptio"...) at src/utils.cpp:500
#9  0x0000559d984d661d in newsboat::RssParser::download_filterplugin (this=0x7fff48a80140, filter="cat", uri=...) at src/rssparser.cpp:292
#10 0x0000559d984d7e6f in newsboat::RssParser::retrieve_uri (this=0x7fff48a80140, uri="http://localhost:8000") at src/rssparser.cpp:172
#11 0x0000559d984da21c in newsboat::RssParser::parse (this=this@entry=0x7fff48a80140) at src/rssparser.cpp:52
#12 0x0000559d9857d4b1 in newsboat::Reloader::reload (this=0x559d98c24580, pos=pos@entry=614, show_progress=show_progress@entry=false, unattended=unattended@entry=false, easyhandle=easyhandle@entry=0x0) at src/reloader.cpp:94
#13 0x0000559d984ef1b6 in newsboat::FeedListFormAction::process_operation (this=0x559e0e82f510, op=1218970592, automatic=false, args=0x7fff48a803b0) at src/feedlistformaction.cpp:121
#14 0x0000559d984bf6df in newsboat::View::run (this=0x7fff48a80bb0) at /usr/include/c++/10/bits/shared_ptr_base.h:1324
#15 0x0000559d984c8e89 in newsboat::Controller::run (this=this@entry=0x7fff48a80cd0, args=...) at src/controller.cpp:522
#16 0x0000559d984875f7 in main (argc=1, argv=0x7fff48a81068) at newsboat.cpp:254
```

Details on frame 8:

```
#8  0x000055810ba3d056 in newsboat::utils::run_program (argv=0x7ffdbd40b088, argv@entry=0x7ffdbd40b070, 
    input="<rss version=\"2.0\">\n<channel>\n    <title>\300\301\302\303\304\305\306\307\310\311\312\313\314\315\316\317\320\321\322\323\324\325\326\327\330\331\332\333\334\335\336\337\340\341\342\343\344\345\346\347\350\351\352\353\354\355\356\357\360\361\362\363\364\365\366\367\370\371\372\373\374\375\376\377</title>\n    <link>http://noticias.uol.com.br/</link>\n    <description>timas Notias</descriptio"...) at src/utils.cpp:500
500             return std::string(utils::bridged::run_program(rs_argv, input));
```

From further frames we see that the exception is thrown by `Str` — that's `input` here. So Newsboat panics because of non-UTF-8 input to `filter:`.

**Comment by dennisschagt** [comment]
I somehow misunderstood this issue.
Now that I read it correctly (and tested/bisected locally), it looks like this is fixed by https://github.com/newsboat/newsboat/pull/2214.
I needed to replace the "echo" in the filter by "cat" to actually pass the data back to newsboat for parsing.
After doing that, the feed was loaded as expected.

However, there is still a crash possible if a server is misconfigured, e.g. sending us text encoded in iso-8859-1 while telling us (via the HTTP headers) that the charset is utf-8.
In that case, we still pass the data as-is into Rust functions, causing a crash.
I have some idea for a possible fix, and will create a PR if it works.
