### ISSUE TITLE
crash on some articles

### ISSUE THREAD

**Issue by sss123next** [newsboat/newsboat#1738]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
newsboat -v
Newsboat 2.24.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2021 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2021 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat 2.24.0
System: Linux 5.13.8 (x86_64)
Compiler: g++ 7.5.0
ncurses: ncurses 6.2.20200212 (compiled with 6.2)
libcurl: libcurl/7.77.0 GnuTLS/3.6.16 zlib/1.2.11 libidn2/2.3.0 nghttp2/1.41.0 OpenLDAP/2.4.57 (compiled with 7.74.0)
SQLite: 3.32.3 (compiled with 3.31.1)
libxml2: compiled with 2.9.10
```
Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
cat ~/.newsboat/config 
confirm-exit yes
download-full-page yes
download-retries 13
download-timeout 90
max-browser-tabs 100
refresh-on-startup yes
reload-threads 8
reload-time 30

```

Steps to reproduce the issue:

1. add `https://www.netbsd.org/changes/rss-netbsd.xml` to uris

2. open articled `New Security Advisory: NetBSD-SA2021-002`

trace:
```
(gdb) c
Continuing.

Thread 1 "newsboat" received signal SIGABRT, Aborted.
0x00007fe0376cfaba in raise () from /gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/libc.so.6
(gdb) where
#0  0x00007fe0376cfaba in raise () from /gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/libc.so.6
#1  0x00007fe0376d0bf5 in abort () from /gnu/store/fa6wj5bxkj5ll1d7292a70knmyl7a0cr-glibc-2.31/lib/libc.so.6
#2  0x00007fe037a4bf75 in __gnu_cxx::__verbose_terminate_handler() () from /gnu/store/01b4w3m6mp55y531kyi1g8shh722kwqm-gcc-7.5.0-lib/lib/libstdc++.so.6
#3  0x00007fe037a49d56 in __cxxabiv1::__terminate(void (*)()) () from /gnu/store/01b4w3m6mp55y531kyi1g8shh722kwqm-gcc-7.5.0-lib/lib/libstdc++.so.6
#4  0x00007fe037a49da1 in std::terminate() () from /gnu/store/01b4w3m6mp55y531kyi1g8shh722kwqm-gcc-7.5.0-lib/lib/libstdc++.so.6
#5  0x00007fe037a49fe3 in __cxa_throw () from /gnu/store/01b4w3m6mp55y531kyi1g8shh722kwqm-gcc-7.5.0-lib/lib/libstdc++.so.6
#6  0x00000000005607b7 in void rust::cxxbridge1::panic<std::invalid_argument>(char const*) ()
#7  0x00000000005608b5 in rust::cxxbridge1::Str::Str(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#8  0x000000000054aac1 in newsboat::utils::utf8_to_locale(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
#9  0x000000000051531f in newsboat::item_renderer::to_stfl_list(newsboat::ConfigContainer&, std::shared_ptr<newsboat::RssItem>, unsigned int, unsigned int, newsboat::RegexManager*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, newsboat::LinkType>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, newsboat::LinkType> > >&) ()
#10 0x0000000000482e58 in newsboat::ItemViewFormAction::prepare() ()
#11 0x0000000000443fa0 in newsboat::View::run() ()
#12 0x000000000044ea77 in newsboat::Controller::run(newsboat::CliArgsParser const&) ()
#13 0x000000000040c740 in main ()
```

**Comment by Minoru** [comment]
Reproduced on current `master`, r2.24-91-ge3c4c. This is yet another manifestation of #1344, on which I'm still working (albeit slowly).

Thanks for the report! I'll keep this issue open until #1344 is fixed, and then I'll come back and check that this is fixed too.
