### ISSUE TITLE
segfault when resizing during refresh

### ISSUE THREAD

**Issue by dopefishh** [newsboat/newsboat#2315]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:

`commit b8fb4ae0cd6d01fb8fa47f4efa30790beec33ba5 (HEAD -> master, origin/master, origin/HEAD)`

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
browser "firefox %u"
max-items 50
refresh-on-startup yes
```

Steps to reproduce the issue:

1. start newsboat

2. resize terminal during refresh (at startup or when pressing R)

This does not happen all the time but when you frantically resize during refreshing it happens almost every session.
It's not just that this happens when you pathologically resize, it also happen occasionally when I just resize one time during refreshing but this is harder to reproduce.

gdb output:
```
Thread 3 "newsboat" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 28195.28247]
0x00007ffff7bb0723 in wnoutrefresh () from target:/lib/x86_64-linux-gnu/libncursesw.so.6
```

stack trace:
```
#0  0x00007ffff7bb0723 in wnoutrefresh ()
   from target:/lib/x86_64-linux-gnu/libncursesw.so.6
#1  0x00007ffff7bb0b27 in wrefresh ()
   from target:/lib/x86_64-linux-gnu/libncursesw.so.6
#2  0x00007ffff7beba0e in stfl_form_run () from target:/lib/libstfl.so.0
#3  0x00007ffff7bea8dd in stfl_run () from target:/lib/libstfl.so.0
#4  0x000055555570664c in newsboat::Stfl::Form::run (this=0x555555c87558,
    timeout=<optimized out>) at src/stflpp.cpp:47
#5  0x000055555561dc8e in newsboat::FormAction::draw_form (
    this=<optimized out>) at src/formaction.cpp:76
#6  0x00005555556db777 in newsboat::View::force_redraw (this=<optimized out>)
    at /usr/include/c++/10/bits/shared_ptr_base.h:1324
#7  0x00005555556a364c in newsboat::Reloader::reload_all (
    this=0x555555a94140, unattended=<optimized out>) at src/reloader.cpp:221
#8  0x00005555556a3a4f in operator() (__closure=0x555555c631f8)
    at src/reloader.cpp:46
#9  std::__invoke_impl<void, newsboat::Reloader::start_reload_all_thread(const std::vector<int>&)::<lambda()> > (__f=...)
    at /usr/include/c++/10/bits/invoke.h:60
#10 std::__invoke<newsboat::Reloader::start_reload_all_thread(const std::vector<int>&)::<lambda()> > (__fn=...) at /usr/include/c++/10/bits/invoke.h:95
#11 std::thread::_Invoker<std::tuple<newsboat::Reloader::start_reload_all_thread(const std::vector<int>&)::<lambda()> > >::_M_invoke<0> (
    this=0x555555c631f8) at /usr/include/c++/10/thread:264
#12 std::thread::_Invoker<std::tuple<newsboat::Reloader::start_reload_all_thread(const std::vector<int>&)::<lambda()> > >::operator() (this=0x555555c631f8)
    at /usr/include/c++/10/thread:271
#13 std::thread::_State_impl<std::thread::_Invoker<std::tuple<newsboat::Reloader::start_reload_all_thread(const std::vector<int>&)::<lambda()> > > >::_M_run(void) (this=0x555555c631f0) at /usr/include/c++/10/thread:215
#14 0x00007ffff7a69ed0 in ?? ()
   from target:/lib/x86_64-linux-gnu/libstdc++.so.6
#15 0x00007ffff7f90ea7 in start_thread (arg=<optimized out>)
    at pthread_create.c:477
#16 0x00007ffff78a8a2f in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Other info you think is relevant**:

**Comment by dennisschagt** [comment]
I don't have time to look into it at the moment, but I can reproduce it locally.
It looks like this is caused by calling into ncurses from multiple threads:
```
coredumpctl debug 
           PID: 1788 (newsboat)
           UID: 1000 (dennis)
           GID: 1000 (dennis)
        Signal: 11 (SEGV)
     Timestamp: Wed 2023-01-18 12:46:31 CET (22s ago)
  Command Line: newsboat
    Executable: /usr/bin/newsboat
 Control Group: /user.slice/user-1000.slice/session-1.scope
          Unit: session-1.scope
         Slice: user-1000.slice
       Session: 1
     Owner UID: 1000 (dennis)
         ...
  Size on Disk: 4.8M
       Message: Process 1788 (newsboat) of user 1000 dumped core.
                
                Stack trace of thread 4433:
                #0  0x00007f0f309e3d12 n/a (libncursesw.so.6 + 0x1ad12)
                #1  0x00007f0f309e3603 waddch (libncursesw.so.6 + 0x1a603)
                #2  0x00007f0f30a583e8 n/a (libstfl.so.0 + 0x83e8)
                #3  0x00007f0f30a55781 stfl_form_run (libstfl.so.0 + 0x5781)
                #4  0x00007f0f30a5427b stfl_run (libstfl.so.0 + 0x427b)
                #5  0x000055f4bfd3c591 n/a (newsboat + 0x1ef591)
                #6  0x000055f4bfd0cd12 n/a (newsboat + 0x1bfd12)
                #7  0x000055f4bfcf443d n/a (newsboat + 0x1a743d)
                #8  0x000055f4bfcf4884 n/a (newsboat + 0x1a7884)
                #9  0x000055f4bfcce155 n/a (newsboat + 0x181155)
                #10 0x000055f4bfcce6ba n/a (newsboat + 0x1816ba)
                #11 0x000055f4bfccbfa2 n/a (newsboat + 0x17efa2)
                #12 0x000055f4bfccce45 n/a (newsboat + 0x17fe45)
                #13 0x000055f4bfccd4e7 n/a (newsboat + 0x1804e7)
                #14 0x00007f0f306d62f3 execute_native_thread_routine (libstdc++.so.6 + 0xd62f3)
                #15 0x00007f0f3049f8fd n/a (libc.so.6 + 0x868fd)
                #16 0x00007f0f30521a60 n/a (libc.so.6 + 0x108a60)
                
                Stack trace of thread 1788:
                #0  0x00007f0f30a04f50 wresize (libncursesw.so.6 + 0x3bf50)
                #1  0x00007f0f30a1ec21 n/a (libncursesw.so.6 + 0x55c21)
                #2  0x00007f0f30a07e3b resize_term_sp (libncursesw.so.6 + 0x3ee3b)
                #3  0x00007f0f30a0d8ba resizeterm_sp (libncursesw.so.6 + 0x448ba)
                #4  0x00007f0f30a08963 _nc_update_screensize (libncursesw.so.6 + 0x3f963)
                #5  0x00007f0f309ea376 n/a (libncursesw.so.6 + 0x21376)
                #6  0x00007f0f30a02d5a wget_wch (libncursesw.so.6 + 0x39d5a)
                #7  0x00007f0f30a5582a stfl_form_run (libstfl.so.0 + 0x582a)
                #8  0x00007f0f30a5427b stfl_run (libstfl.so.0 + 0x427b)
                #9  0x000055f4bfd3c591 n/a (newsboat + 0x1ef591)
                #10 0x000055f4bfc31069 n/a (newsboat + 0xe4069)
                #11 0x000055f4bfd183e6 n/a (newsboat + 0x1cb3e6)
                #12 0x000055f4bfbeee50 n/a (newsboat + 0xa1e50)
                #13 0x000055f4bfbbea51 n/a (newsboat + 0x71a51)
                #14 0x00007f0f3043c290 n/a (libc.so.6 + 0x23290)
                #15 0x00007f0f3043c34a __libc_start_main (libc.so.6 + 0x2334a)
                #16 0x000055f4bfbc4575 n/a (newsboat + 0x77575)
                
                Stack trace of thread 1835:
                #0  0x00007f0f304e67c5 clock_nanosleep (libc.so.6 + 0xcd7c5)
                #1  0x00007f0f304eb2d7 __nanosleep (libc.so.6 + 0xd22d7)
                #2  0x00007f0f304eb20e sleep (libc.so.6 + 0xd220e)
                #3  0x000055f4bfcceca6 n/a (newsboat + 0x181ca6)
                #4  0x00007f0f306d62f3 execute_native_thread_routine (libstdc++.so.6 + 0xd62f3)
                #5  0x00007f0f3049f8fd n/a (libc.so.6 + 0x868fd)
                #6  0x00007f0f30521a60 n/a (libc.so.6 + 0x108a60)
                ELF object binary architecture: AMD x86-64
```
