### ISSUE TITLE
Newsboat crashes at start when you scroll through the list of feeds while it still loads the feeds

### ISSUE THREAD

**Issue by PietJanHein** [newsboat/newsboat#2592]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:  2.33.0

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):  

```
INSERT COPY HERE It would help if GitHub would support all files and doesn't force to first make a zip, while not even supporting tar. Yeah, really Linux-loving MicroSoft. :roll_eyes: 
[newsboatconfig.zip](https://github.com/newsboat/newsboat/files/13226941/newsboatconfig.zip)

```

Steps to reproduce the issue:

1. Set the keyboard to have a higher repeat rate than default on X11, in my case 70, for example with xset r rate 200 70 (200 ms repeat delay and 70 repeats per second) in the case of X11

2. Start scrolling through the list of feeds, in my case by pressing the down-arrow which moves the highlighted feed to one feed lower. while the feeds are still getting loaded

3. Newsboat will crash and exit. 

**Other info you think is relevant**:
It doesn't matter if you scroll through the list of feeds which already got loaded or through feeds which haven't been loaded, with 100% consistency newsboat crashes if you scroll through the list feeds while it is still loading feeds. It seems to be related to the speed with which you scroll through the list of feeds. Apparently doing so interrupts the loading of the data of the feeds in newsboat (you see that slowing down, or at least the notification of what gets loaded) which makes it crash.

**Comment by Minoru** [comment]
Nice find! I reproduced on ca977d51a0ea9bc08d302d9ce58e424090823a87 by jacking up the key repeat speed in Gnome (Settings → Accessibility → Typing → Repeat keys) and holding down <kbd>Up</kbd> and <kbd>Down</kbd> while Newsboat is starting (I have `auto-reload yes`).

The stacktrace:

```
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
#1  0x00007fd436c89d9f in __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  0x00007fd436c3af32 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007fd436c25472 in __GI_abort () at ./stdlib/abort.c:79
#4  0x00007fd4370b5b22 in stfl_parser () from /lib/libstfl.so.0
#5  0x00007fd4370b3d8f in stfl_modify () from /lib/libstfl.so.0
#6  0x0000561592120eb0 in newsboat::Stfl::Form::modify (this=0x5616604dab68, name=..., mode=..., text=...) at src/stflpp.cpp:95
#7  0x000056159208bfe5 in newsboat::ListWidgetBackend::render (this=0x5616604dabe8) at src/listwidgetbackend.cpp:98
#8  0x000056159208c66e in newsboat::ListWidgetBackend::update_position (this=<optimized out>, pos=<optimized out>, new_scroll_offset=<optimized out>) at src/listwidgetbackend.cpp:76
#9  0x000056159203c8e3 in newsboat::ListMovementControl<newsboat::ListWidgetBackend>::set_position (pos=210, this=0x5616604dabe8) at include/listmovementcontrol.h:180
#10 newsboat::ListMovementControl<newsboat::ListWidgetBackend>::move_down (wrap_scroll=<optimized out>, this=0x5616604dabe8) at include/listmovementcontrol.h:64
#11 newsboat::FormAction::handle_list_operations (this=this@entry=0x5616604dab50, list=..., op=op@entry=newsboat::OP_SK_DOWN) at src/formaction.cpp:348
#12 0x000056159208a7b4 in newsboat::ListFormAction::process_operation (this=this@entry=0x5616604dab50, op=op@entry=newsboat::OP_SK_DOWN) at src/listformaction.cpp:53
#13 0x000056159202a866 in newsboat::FeedListFormAction::process_operation (this=0x5616604dab50, op=newsboat::OP_SK_DOWN, args=..., bindingType=newsboat::BindingType::BindKey) at src/feedlistformaction.cpp:525
#14 0x0000561592100e85 in newsboat::View::run (this=0x7ffe898a1210) at src/view.cpp:240
#15 0x0000561591ffeef7 in newsboat::Controller::run (this=this@entry=0x7ffe898a1360, args=...) at src/controller.cpp:554
#16 0x0000561591fd0a54 in main (argc=<optimized out>, argv=<optimized out>) at newsboat.cpp:258
```

I also think I saw a glimpse of an STFL error saying it can't parse `''` (empty string).

Perhaps we have a race between `Reloader` and the main event loop? Might be worth reproducing with ThreadSanitizer too.

**Comment by Minoru** [comment]
This might be a duplicate of #1723 BTW.

**Comment by PietJanHein** [comment]
> This might be a duplicate of #1723 BTW.

It looks like it. This reply might hit the nail on the head. https://github.com/newsboat/newsboat/issues/1723#issuecomment-887573558 
It would explain why this only happens with shorter intervals between inputs (higher repeat-rate for the keyboard).
