### ISSUE TITLE
Newsboat crash on start

### ISSUE THREAD

**Issue by tpaau-17DB** [newsboat/newsboat#2909]
version:
```
Newsboat r2.37
```

config:
```
#show-read-feeds no
auto-reload yes

external-url-viewer "urlscan -dc -r 'firefox {}'"

bind-key j down
bind-key k up
bind-key j next articlelist
bind-key k prev articlelist
bind-key J next-feed articlelist
bind-key K prev-feed articlelist
bind-key G end
bind-key g home
bind-key d pagedown
bind-key u pageup
bind-key l open
bind-key h quit
bind-key a toggle-article-read
bind-key n next-unread
bind-key N prev-unread
bind-key D pb-download
bind-key U show-urls
bind-key x pb-delete

color listnormal cyan default
color listfocus black yellow standout bold
color listnormal_unread blue default
color listfocus_unread yellow default bold
color info red black bold
color article white default bold

browser firefox
macro , open-in-browser
macro t set browser "qndl" ; open-in-browser ; set browser firefox
macro a set browser "tsp youtube-dl --add-metadata -xic -f bestaudio/best" ; open-in-browser ; set browser firefox
macro v set browser "setsid -f mpv" ; open-in-browser ; set browser firefox
macro w set browser "lynx" ; open-in-browser ; set browser firefox
macro p set browser "dmenuhandler" ; open-in-browser ; set browser firefox
macro c set browser "xsel -b <<<" ; open-in-browser ; set browser firefox
macro C set browser "youtube-viewer --comments=%u" ; open-in-browser ; set browser firefox

highlight all "---.*---" yellow
highlight feedlist ".*(0/0))" black
highlight article "(^Feed:.*|^Title:.*|^Author:.*)" cyan default bold
highlight article "(^Link:.*|^Date:.*)" default default
highlight article "https?://[^ ]+" green default
highlight article "^(Title):.*$" blue default
highlight article "\\[[0-9][0-9]*\\]" magenta default bold
highlight article "\\[image\\ [0-9]+\\]" green default bold
highlight article "\\[embedded flash: [0-9][0-9]*\\]" green default bold
highlight article ":.*\\(link\\)$" cyan default
highlight article ":.*\\(image\\)$" blue default
highlight article ":.*\\(embedded flash\\)$" magenta default

download-path "~/Videos/downloaded/newsboat"
player "mpv"
```

gdb output:
```
malloc(): unaligned fastbin chunk detected                                                                                                                                                                        
   1         (0/0) ---Youtube---                                                                                                                                                                                  
   2         (0/0) ---Music---            Thread 1 "newsboat" received signal SIGABRT, Aborted.                                                                                                                   
   3        (0/19) Mental Outlaw                                                               ^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OB^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OA^[OADownloading 4.06 K source file /usr/src/debug/glibc/glibc/nptl/pthread_kill.c                                                                    
__pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44                                                                                         
44 8          return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;                                                                                                                           
(gdb) backtrace
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44                                                                                     
#1  0x00007ffff76a5463 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78                                                                                                        
#2  0x00007ffff764c120 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26                                                                                                                             
#3  0x00007ffff76334c3 in __GI_abort () at abort.c:79                                                                                                                                                             
#4  0x00007ffff7634354 in __libc_message_impl (fmt=fmt@entry=0x7ffff77c22f5 "%s\n") at ../sysdeps/posix/libc_fatal.c:132                                                                                          
#5  0x00007ffff76af765 in malloc_printerr (str=str@entry=0x7ffff77c5828 "malloc(): unaligned fastbin chunk detected") at malloc.c:5772                                                                            
#6  0x00007ffff76b2f54 in _int_malloc (av=av@entry=0x7ffff77f6ac0 <main_arena>, bytes=bytes@entry=35) at malloc.c:3929                                                                                            
#7  0x00007ffff76b3ef4 in __GI___libc_malloc (bytes=bytes@entry=35) at malloc.c:3336                                                                                                                              
#8  0x00007ffff78ae745 in operator new (sz=sz@entry=35) at /usr/src/debug/gcc/gcc/libstdc++-v3/libsupc++/new_op.cc:50                                                                                             
#9  0x0000000100156e35 in std::__new_allocator<char>::allocate (this=<optimized out>, __n=35) at /usr/include/c++/14.2.1/bits/new_allocator.h:151                                                                 
#10 std::allocator_traits<std::allocator<char> >::allocate (__a=..., __n=35) at /usr/include/c++/14.2.1/bits/alloc_traits.h:478                                                                                   
#11 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_allocate (__a=..., __n=35) at /usr/include/c++/14.2.1/bits/basic_string.h:131                                             
#12 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create (this=0x100878cc0, __capacity=<synthetic pointer>: <optimized out>, __old_capacity=0)                              
    at /usr/include/c++/14.2.1/bits/basic_string.tcc:159                                                                                                                                                          
#13 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_construct<char*> (this=0x100878cc0, __beg=0x100768430 "  19        (0/16) Sebastian Lague", __end=0x100768452 "")         
    at /usr/include/c++/14.2.1/bits/basic_string.tcc:229                                                                                                                                                          
#14 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string (this=0x100878cc0, __str="  19        (0/16) Sebastian Lague")                                                  
    at /usr/include/c++/14.2.1/bits/basic_string.h:556                                                                                                                                                            
#15 newsboat::StflRichText::StflRichText (this=0x100878cc0) at include/stflrichtext.h:14                                                                                                                          
#16 std::__new_allocator<newsboat::StflRichText>::construct<newsboat::StflRichText, newsboat::StflRichText const&> (this=0x1005aa9b0, __p=0x100878cc0) at /usr/include/c++/14.2.1/bits/new_allocator.h:191        
#17 std::allocator_traits<std::allocator<newsboat::StflRichText> >::construct<newsboat::StflRichText, newsboat::StflRichText const&> (__a=..., __p=0x100878cc0)                                                   
    at /usr/include/c++/14.2.1/bits/alloc_traits.h:534                                                                                                                                                            
#18 std::vector<newsboat::StflRichText, std::allocator<newsboat::StflRichText> >::push_back (this=0x1005aa9b0, __x=...) at /usr/include/c++/14.2.1/bits/stl_vector.h:1288                                         
#19 newsboat::ListFormatter::set_line (this=0x1005aa9b0, itempos=itempos@entry=4294967295, text=...) at src/listformatter.cpp:35                                                                                  
#20 0x00000001001575ec in newsboat::ListFormatter::add_line (this=<optimized out>, text=...) at src/listformatter.cpp:23                                                                                          
#21 0x0000000100158e6b in newsboat::ListWidgetBackend::render (this=0x1005aa980) at src/listwidgetbackend.cpp:95                                                                                                  
#22 0x00000001000fd7a2 in newsboat::ListMovementControl<newsboat::ListWidgetBackend>::move_to_first (this=<optimized out>) at include/listmovementcontrol.h:76                                                    
#23 newsboat::ListMovementControl<newsboat::ListWidgetBackend>::move_down (this=0x1005aa980, wrap_scroll=false) at include/listmovementcontrol.h:67                                                               
#24 newsboat::FormAction::handle_list_operations (this=this@entry=0x1005aa870, list=..., op=<optimized out>) at src/formaction.cpp:350                                                                            
#25 0x0000000100155649 in newsboat::ListFormAction::process_operation (this=this@entry=0x1005aa870, op=<optimized out>) at src/listformaction.cpp:53
#26 0x00000001000e561f in newsboat::FeedListFormAction::process_operation (this=0x1005aa870, op=<optimized out>, args=std::vector of length 0, capacity 0, bindingType=newsboat::BindingType::BindKey)
    at src/feedlistformaction.cpp:520
#27 0x00000001001f655f in newsboat::View::run (this=<optimized out>) at src/view.cpp:235
#28 0x00000001000881f7 in newsboat::Controller::run (this=this@entry=0x7fffffffe1c0, args=...) at src/controller.cpp:576
#29 0x0000000100056ed6 in main (argc=1, argv=<optimized out>) at newsboat.cpp:290
```
Sorry, I know it's a little random and deformed.

Steps to reproduce the issue:

1. Open newsboat

2. Quickly go up and down, preferably with a scroll wheel while newsboat is retrieving rss feeds

3. Newsboat crashes

**Other info you think is relevant**:
I use Arch BTW

**Comment by juntuu** [comment]
Duplicate of #2592

Thanks for the additional stacktrace.

**Comment by tpaau-17DB** [comment]
Okay, closing then.

> Duplicate of #2592
> 
> Thanks for the additional stacktrace.
