### ISSUE TITLE
segmentation fault after pressing and holding `n`

### ISSUE THREAD

**Issue by cgahr** [newsboat/newsboat#2952]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
Newsboat 2.37.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2024 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2024 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles:
- JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json
- optional-lite library, licensed under the Boost Software License: https://github.com/martinmoene/optional-lite
- expected-lite library, licensed under the Boost Software License: https://github.com/martinmoene/expected-lite

Newsboat 2.37.0
System: Linux 6.6.63 (x86_64)
Compiler: g++ 13.3.0
ncurses: ncurses 6.4.20221231 (compiled with 6.4)
libcurl: libcurl/8.11.0 OpenSSL/3.3.2 zlib/1.3.1 brotli/1.1.0 zstd/1.5.6 libidn2/2.3.7 libpsl/0.21.5 libssh2/1.11.1 nghttp2/1.64.0 (compiled with 8.11.0)
SQLite: 3.46.1 (compiled with 3.46.1)
libxml2: compiled with 2.13.4
```

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
max-items 0
browser /nix/store/5y57az40nygm6x6y9yrndfm12xj70r4j-lynx-2.9.0dev.12/bin/lynx
reload-threads 5
auto-reload yes
reload-time 60
prepopulate-query-feeds yes

```

Steps to reproduce the issue:

1. run `newsboat`

2. immediately press and hold `n`

**Other info you think is relevant**:

- I installed `newsboat` via nix
- terminal output directly after crashing (scrambled):
```
double free or corruption (fasttop)                                                                                    
  39         (0/0) http://gzsh: abort (core dumped)  newsboat
```

**Comment by cgahr** [comment]
Core dump:
```
     Timestamp: Fri 2024-12-13 15:28:07 CET (1min 24s ago)
  Command Line: newsboat
    Executable: /nix/store/ym6301vgjs7qv751yayx07hpymzqw6pl-newsboat-2.37/bin/newsboat
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/foot.service
          Unit: user@1000.service
     User Unit: foot.service
         Slice: user-1000.slice
     Owner UID: 1000 (cgahr)
       Boot ID: ab270d173531419db0f2559c4444f41c
    Machine ID: a28f08d03893435499276d897f05431b
      Hostname: nixos
       Storage: /var/lib/systemd/coredump/core.newsboat.1000.ab270d173531419db0f2559c4444f41c.451344.1734100087000000.zst (present)
  Size on Disk: 3.8M
       Message: Process 451344 (newsboat) of user 1000 dumped core.
                
                Module libbrotlicommon.so.1 without build-id.
                Module libkeyutils.so.1 without build-id.
                Module libkrb5support.so.0 without build-id.
                Module libcom_err.so.3 without build-id.
                Module libk5crypto.so.3 without build-id.
                Module libkrb5.so.3 without build-id.
                Module libunistring.so.5 without build-id.
                Module libbrotlidec.so.1 without build-id.
                Module libzstd.so.1 without build-id.
                Module libgssapi_krb5.so.2 without build-id.
                Module libpsl.so.5 without build-id.
                Module libssh2.so.1 without build-id.
                Module libidn2.so.0 without build-id.
                Module libnghttp2.so.14 without build-id.
                Module libz.so.1 without build-id.
                Module libgcc_s.so.1 without build-id.
                Module libstdc++.so.6 without build-id.
                Module libncursesw.so.6 without build-id.
                Module libjson-c.so.5 without build-id.
                Module libstfl.so.0 without build-id.
                Module libxml2.so.2 without build-id.
                Module newsboat without build-id.
                Stack trace of thread 451344:
                #0  0x00007f8fbac99a9c __pthread_kill_implementation (libc.so.6 + 0x92a9c)
                #1  0x00007f8fbac47576 raise (libc.so.6 + 0x40576)
                #2  0x00007f8fbac2f935 abort (libc.so.6 + 0x28935)
                #3  0x00007f8fbaeacc2b _ZN9__gnu_cxx27__verbose_terminate_handlerEv.cold (libstdc++.so.6 + 0xacc2b)
                #4  0x00007f8fbaebc20a _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xbc20a)
                #5  0x00007f8fbaebc275 _ZSt9terminatev (libstdc++.so.6 + 0xbc275)
                #6  0x00007f8fbaebc518 __cxa_rethrow (libstdc++.so.6 + 0xbc518)
                #7  0x0000000000421665 _ZNSt8_Rb_treeImSt4pairIKmNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEESt10_Select1stIS8_ESt4lessImESaIS8_EE7_M_copyILb0ENSE_11_Alloc_nodeEEEPSt13_Rb_tree_nodeIS8_ESJ_PSt18_Rb_tree_node_baseRT0_.isra.0.cold (newsboat + 0x21665)
                #8  0x0000000000528bcd _ZNK8newsboat13ListFormatter11format_listB5cxx11Ev (newsboat + 0x128bcd)
                #9  0x000000000052a9b6 _ZN8newsboat17ListWidgetBackend6renderEv (newsboat + 0x12a9b6)
                #10 0x00000000004bfd18 _ZN8newsboat18FeedListFormAction24jump_to_next_unread_feedERj (newsboat + 0xbfd18)
                #11 0x00000000004c3869 _ZN8newsboat18FeedListFormAction17process_operationENS_9OperationERKSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS8_EENS_11BindingTypeE (newsboat + 0xc3869)
                #12 0x00000000005b50e5 _ZN8newsboat4View3runEv (newsboat + 0x1b50e5)
                #13 0x00000000004715ef _ZN8newsboat10Controller3runERKNS_13CliArgsParserE (newsboat + 0x715ef)
                #14 0x000000000043ea37 main (newsboat + 0x3ea37)
                #15 0x00007f8fbac3127e __libc_start_call_main (libc.so.6 + 0x2a27e)
                #16 0x00007f8fbac31339 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a339)
                #17 0x0000000000444755 _start (newsboat + 0x44755)
                
                Stack trace of thread 451347:
                #0  0x00007f8fbad162a1 __tfind (libc.so.6 + 0x10f2a1)
                #1  0x00007f8fbac32e06 __gconv_find_transform (libc.so.6 + 0x2be06)
                #2  0x00007f8fbac318f2 __gconv_open (libc.so.6 + 0x2a8f2)
                #3  0x00007f8fbac31608 iconv_open (libc.so.6 + 0x2a608)
                #4  0x00007f8fbb2413ea stfl_ipool_fromwc (libstfl.so.0 + 0x83ea)
                #5  0x00000000005dc721 _ZN8newsboat5utils8wstr2strERKNSt7__cxx1112basic_stringIwSt11char_traitsIwESaIwEEE (newsboat + 0x1dc721)
                #6  0x0000000000528732 _ZN8newsboat13ListFormatter8set_lineEjRKNS_12StflRichTextE (newsboat + 0x128732)
                #7  0x000000000052a921 _ZN8newsboat17ListWidgetBackend6renderEv (newsboat + 0x12a921)
                #8  0x000000000052ae69 _ZN8newsboat17ListWidgetBackend23invalidate_list_contentEjSt8functionIFNS_12StflRichTextEjjEE (newsboat + 0x12ae69)
                #9  0x00000000004c0449 _ZN8newsboat18FeedListFormAction12set_feedlistERSt6vectorISt10shared_ptrINS_7RssFeedEESaIS4_EE (newsboat + 0xc0449)
                #10 0x00000000005adfa6 _ZN8newsboat4View12set_feedlistESt6vectorISt10shared_ptrINS_7RssFeedEESaIS4_EE (newsboat + 0x1adfa6)
                #11 0x000000000046bcbb _ZN8newsboat10Controller12replace_feedESt10shared_ptrINS_7RssFeedEES3_jb (newsboat + 0x6bcbb)
                #12 0x0000000000568087 _ZN8newsboat8Reloader6reloadEjRNS_10CurlHandleEbb (newsboat + 0x168087)
                #13 0x0000000000568e63 _ZNSt17_Function_handlerIFvjjEZN8newsboat8Reloader19reload_indexes_implESt6vectorIjSaIjEEbEUljjE0_E9_M_invokeERKSt9_Any_dataOjSB_ (newsboat + 0x168e63)
                #14 0x00000000005659f8 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN8newsboat8Reloader27partition_reload_to_threadsESt8functionIFvjjEEjEUlvE_EEEEE6_M_runEv (newsboat + 0x1659f8)
                #15 0x00007f8fbaee86d3 execute_native_thread_routine (libstdc++.so.6 + 0xe86d3)
                #16 0x00007f8fbac97d02 start_thread (libc.so.6 + 0x90d02)
                #17 0x00007f8fbad173ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 451345:
                #0  0x00007f8fbace1895 clock_nanosleep@GLIBC_2.2.5 (libc.so.6 + 0xda895)
                #1  0x00007f8fbacec927 __nanosleep (libc.so.6 + 0xe5927)
                #2  0x00007f8fbacfdfbe sleep (libc.so.6 + 0xf6fbe)
                #3  0x000000000056ae7d _ZN8newsboat12ReloadThreadclEv (newsboat + 0x16ae7d)
                #4  0x00007f8fbaee86d3 execute_native_thread_routine (libstdc++.so.6 + 0xe86d3)
                #5  0x00007f8fbac97d02 start_thread (libc.so.6 + 0x90d02)
                #6  0x00007f8fbad173ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 451346:
                #0  0x00007f8fbad090af __poll (libc.so.6 + 0x1020af)
                #1  0x00007f8fbb418308 Curl_poll (libcurl.so.4 + 0x6f308)
                #2  0x00007f8fbb40f4f2 multi_wait.part.0 (libcurl.so.4 + 0x664f2)
                #3  0x00007f8fbb40f64a curl_multi_poll (libcurl.so.4 + 0x6664a)
                #4  0x00007f8fbb3dd083 curl_easy_perform (libcurl.so.4 + 0x34083)
                #5  0x00000000007668a6 _ZN5rsspp6Parser9parse_urlERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERN8newsboat10CurlHandleElS8_PNS9_9RemoteApiES8_ (newsboat + 0x3668a6)
                #6  0x00000000004ca972 _ZN8newsboat13FeedRetriever13download_httpERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (newsboat + 0xca972)
                #7  0x00000000004cbeee _ZN8newsboat13FeedRetriever8retrieveERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (newsboat + 0xcbeee)
                #8  0x0000000000567e0c _ZN8newsboat8Reloader6reloadEjRNS_10CurlHandleEbb (newsboat + 0x167e0c)
                #9  0x0000000000568e63 _ZNSt17_Function_handlerIFvjjEZN8newsboat8Reloader19reload_indexes_implESt6vectorIjSaIjEEbEUljjE0_E9_M_invokeERKSt9_Any_dataOjSB_ (newsboat + 0x168e63)
                #10 0x0000000000567062 _ZN8newsboat8Reloader27partition_reload_to_threadsESt8functionIFvjjEEj (newsboat + 0x167062)
                #11 0x000000000056747b _ZN8newsboat8Reloader19reload_indexes_implESt6vectorIjSaIjEEb (newsboat + 0x16747b)
                #12 0x000000000056a0a7 _ZN8newsboat8Reloader10reload_allEb (newsboat + 0x16a0a7)
                #13 0x000000000056a98f _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN8newsboat8Reloader23start_reload_all_threadERKSt6vectorIjSaIjEEEUlvE_EEEEE6_M_runEv (newsboat + 0x16a98f)
                #14 0x00007f8fbaee86d3 execute_native_thread_routine (libstdc++.so.6 + 0xe86d3)
                #15 0x00007f8fbac97d02 start_thread (libc.so.6 + 0x90d02)
                #16 0x00007f8fbad173ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 451350:
                #0  0x00007f8fbad090af __poll (libc.so.6 + 0x1020af)
                #1  0x00007f8fbb418308 Curl_poll (libcurl.so.4 + 0x6f308)
                #2  0x00007f8fbb40f4f2 multi_wait.part.0 (libcurl.so.4 + 0x664f2)
                #3  0x00007f8fbb40f64a curl_multi_poll (libcurl.so.4 + 0x6664a)
                #4  0x00007f8fbb3dd083 curl_easy_perform (libcurl.so.4 + 0x34083)
                #5  0x00000000007668a6 _ZN5rsspp6Parser9parse_urlERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERN8newsboat10CurlHandleElS8_PNS9_9RemoteApiES8_ (newsboat + 0x3668a6)
                #6  0x00000000004ca972 _ZN8newsboat13FeedRetriever13download_httpERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (newsboat + 0xca972)
                #7  0x00000000004cbeee _ZN8newsboat13FeedRetriever8retrieveERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (newsboat + 0xcbeee)
                #8  0x0000000000567e0c _ZN8newsboat8Reloader6reloadEjRNS_10CurlHandleEbb (newsboat + 0x167e0c)
                #9  0x0000000000568e63 _ZNSt17_Function_handlerIFvjjEZN8newsboat8Reloader19reload_indexes_implESt6vectorIjSaIjEEbEUljjE0_E9_M_invokeERKSt9_Any_dataOjSB_ (newsboat + 0x168e63)
                #10 0x00000000005659f8 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN8newsboat8Reloader27partition_reload_to_threadsESt8functionIFvjjEEjEUlvE_EEEEE6_M_runEv (newsboat + 0x1659f8)
                #11 0x00007f8fbaee86d3 execute_native_thread_routine (libstdc++.so.6 + 0xe86d3)
                #12 0x00007f8fbac97d02 start_thread (libc.so.6 + 0x90d02)
                #13 0x00007f8fbad173ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 451405:
                #0  0x00007f8fbad090af __poll (libc.so.6 + 0x1020af)
                #1  0x00007f8fbad66a03 wait_on_socket (libc.so.6 + 0x15fa03)
                #2  0x00007f8fbad67739 __nscd_open_socket (libc.so.6 + 0x160739)
                #3  0x00007f8fbad65061 __nscd_getai (libc.so.6 + 0x15e061)
                #4  0x00007f8fbad4585b getaddrinfo (libc.so.6 + 0x13e85b)
                #5  0x00007f8fbb3d5cb3 Curl_getaddrinfo_ex (libcurl.so.4 + 0x2ccb3)
                #6  0x00007f8fbb3bf60f getaddrinfo_thread (libcurl.so.4 + 0x1660f)
                #7  0x00007f8fbb3d812b curl_thread_create_thunk (libcurl.so.4 + 0x2f12b)
                #8  0x00007f8fbac97d02 start_thread (libc.so.6 + 0x90d02)
                #9  0x00007f8fbad173ac __clone3 (libc.so.6 + 0x1103ac)
                ELF object binary architecture: AMD x86-64
```

**Comment by Minoru** [comment]
I haven't tried to reproduce yet, but the symptoms look like #1723 and #2592.

**Comment by migrgh** [comment]
I can reproduce and got same: what():  std::bad_alloc. Here is my backtrace:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `newsboat -c tmux a'.
Program terminated with signal SIGABRT, Aborted.
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
44	     return INTERNAL_SYSCALL_ERROR_P (ret) ? INTERNAL_SYSCALL_ERRNO (ret) : 0;
[Current thread is 1 (Thread 0x7432a58286c0 (LWP 321))]
(gdb) bt
#0  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=6, no_tid=no_tid@entry=0) at pthread_kill.c:44
#1  0x00007432a6c7ed03 in __pthread_kill_internal (threadid=<optimized out>, signo=6) at pthread_kill.c:78
#2  0x00007432a6c25d1e in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#3  0x00007432a6c0d942 in __GI_abort () at abort.c:79
#4  0x00007432a6e09da9 in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#5  0x00007432a6e1bc2c in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:48
#6  0x00007432a6e09951 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:58
#7  0x00007432a6e0996a in __cxxabiv1::__cxa_rethrow () at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:136
#8  0x000062e0e7ad5a9f in std::_Rb_tree<unsigned long, std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_construct_node<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&> (this=<optimized out>, 
    __node=0x743298159840) at /usr/include/c++/14/bits/stl_tree.h:601
#9  std::_Rb_tree<unsigned long, std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_create_node<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&> (this=<optimized out>) at /usr/include/c++/14/bits/stl_tree.h:610
#10 std::_Rb_tree<unsigned long, std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_Alloc_node::operator()<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&> (this=<optimized out>, __arg={...})
    at /usr/include/c++/14/bits/stl_tree.h:527
#11 std::_Rb_tree<unsigned long, std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_clone_node<false, std::_Rb_tree<unsigned long, std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_Alloc_node> (this=<optimized out>, __x=0x743298148e40, __node_gen=...)
    at /usr/include/c++/14/bits/stl_tree.h:643
#12 std::_Rb_tree<unsigned long, std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_copy<false, std::_Rb_tree<unsigned long, std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::--Type <RET> for more, q to quit, c to continue without paging--
__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_Alloc_node>(std::_Rb_tree_node<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >*, std::_Rb_tree_node_base*, std::_Rb_tree<unsigned long, std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_Alloc_node&) [clone .isra.0] (this=this@entry=0x7432a58267b0, __x=0x743298148e40, __p=__p@entry=0x7432a58267b8, 
    __node_gen=...) at /usr/include/c++/14/bits/stl_tree.h:1892
#13 0x000062e0e7b74b08 in std::_Rb_tree<unsigned long, std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_copy<false, std::_Rb_tree<unsigned long, std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_Alloc_node> (__gen=<synthetic pointer>..., 
    this=0x7432a58267b0, __x=...) at /usr/include/c++/14/bits/stl_tree.h:885
#14 std::_Rb_tree<unsigned long, std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_M_copy (this=0x7432a58267b0, __x=...)
    at /usr/include/c++/14/bits/stl_tree.h:899
#15 std::_Rb_tree<unsigned long, std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_Rb_tree (this=0x7432a58267b0, __x=...)
    at /usr/include/c++/14/bits/stl_tree.h:937
#16 std::_Rb_tree<unsigned long, std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::_Select1st<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::_Rb_tree (this=0x7432a58267b0, __x=...)
    at /usr/include/c++/14/bits/stl_tree.h:933
#17 std::map<unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<unsigned long>, std::allocator<std::pair<unsigned long const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::map (this=0x7432a58267b0)
    at /usr/include/c++/14/bits/stl_map.h:219
#18 newsboat::StflRichText::StflRichText (this=0x7432a5826790) at include/stflrichtext.h:14
#19 newsboat::ListFormatter::format_list[abi:cxx11]() const (this=this@entry=0x62e112371800) at src/listformatter.cpp:44
#20 0x000062e0e7b755c5 in newsboat::ListWidgetBackend::render (this=0x62e1123717d0) at src/listwidgetbackend.cpp:98
#21 0x000062e0e7b75a58 in newsboat::ListMovementControl<newsboat::ListWidgetBackend>::on_list_changed (this=0x62e1123717d0) at include/listmovementcontrol.h:195
#22 newsboat::ListWidgetBackend::invalidate_list_content (this=0x62e1123717d0, line_count=218, get_line_method=...) at src/listwidgetbackend.cpp:64
#23 0x000062e0e7bbd017 in newsboat::FeedListFormAction::set_feedlist (this=0x62e1123716c0, feeds=std::vector of length 218, capacity 218 = {...})
--Type <RET> for more, q to quit, c to continue without paging--
    at src/feedlistformaction.cpp:633
#24 newsboat::View::set_feedlist (this=0x7ffcfdfde380, feeds=std::vector of length 218, capacity 218 = {...}) at src/view.cpp:441
#25 0x000062e0e7b0300b in newsboat::Controller::replace_feed (this=<optimized out>, oldfeed=..., newfeed=..., pos=<optimized out>, unattended=false)
    at src/controller.cpp:752
#26 0x000062e0e7b98fcf in newsboat::Reloader::reload (this=<optimized out>, pos=pos@entry=51, easyhandle=..., show_progress=show_progress@entry=true, 
    unattended=<optimized out>) at src/reloader.cpp:119
#27 0x000062e0e7b9b5b5 in operator() (__closure=0x743298005ce0, start=<optimized out>, end=217) at src/reloader.cpp:265
#28 std::__invoke_impl<void, newsboat::Reloader::reload_indexes_impl(std::vector<unsigned int>, bool)::<lambda(unsigned int, unsigned int)>&, unsigned int, unsigned int> (__f=...) at /usr/include/c++/14/bits/invoke.h:61
#29 std::__invoke_r<void, newsboat::Reloader::reload_indexes_impl(std::vector<unsigned int>, bool)::<lambda(unsigned int, unsigned int)>&, unsigned int, unsigned int> (__fn=...) at /usr/include/c++/14/bits/invoke.h:150
#30 std::_Function_handler<void(unsigned int, unsigned int), newsboat::Reloader::reload_indexes_impl(std::vector<unsigned int>, bool)::<lambda(unsigned int, unsigned int)> >::_M_invoke(const std::_Any_data &, unsigned int &&, unsigned int &&) (__functor=..., __args#0=<optimized out>, __args#1=<optimized out>)
    at /usr/include/c++/14/bits/std_function.h:290
#31 0x000062e0e7b93ce4 in std::function<void(unsigned int, unsigned int)>::operator() (this=0x7432a58277b0, __args#0=<optimized out>, __args#1=<optimized out>)
    at /usr/include/c++/14/bits/std_function.h:591
#32 newsboat::Reloader::partition_reload_to_threads (this=<optimized out>, handle_range=..., num_feeds=<optimized out>) at src/reloader.cpp:185
#33 newsboat::Reloader::reload_indexes_impl (this=this@entry=0x62e1118f11d0, indexes=std::vector of length 218, capacity 218 = {...}, 
    unattended=<optimized out>, unattended@entry=false) at src/reloader.cpp:258
#34 0x000062e0e7b97084 in newsboat::Reloader::reload_all (this=this@entry=0x62e1118f11d0, unattended=unattended@entry=false) at src/reloader.cpp:211
#35 0x000062e0e7b977e2 in operator() (__closure=0x62e1123bcff8) at src/reloader.cpp:47
#36 std::__invoke_impl<void, newsboat::Reloader::start_reload_all_thread(const std::vector<unsigned int>&)::<lambda()> > (__f=...)
    at /usr/include/c++/14/bits/invoke.h:61
#37 std::__invoke<newsboat::Reloader::start_reload_all_thread(const std::vector<unsigned int>&)::<lambda()> > (__fn=...) at /usr/include/c++/14/bits/invoke.h:96
#38 std::thread::_Invoker<std::tuple<newsboat::Reloader::start_reload_all_thread(const std::vector<unsigned int>&)::<lambda()> > >::_M_invoke<0> (
    this=0x62e1123bcff8) at /usr/include/c++/14/bits/std_thread.h:301
#39 std::thread::_Invoker<std::tuple<newsboat::Reloader::start_reload_all_thread(const std::vector<unsigned int>&)::<lambda()> > >::operator() (
    this=0x62e1123bcff8) at /usr/include/c++/14/bits/std_thread.h:308
#40 std::thread::_State_impl<std::thread::_Invoker<std::tuple<newsboat::Reloader::start_reload_all_thread(const std::vector<unsigned int>&)::<lambda()> > > >::_M_run(void) (this=0x62e1123bcff0) at /usr/include/c++/14/bits/std_thread.h:253
#41 0x00007432a6e4b524 in std::execute_native_thread_routine (__p=0x62e1123bcff0) at ../../../../../libstdc++-v3/src/c++11/thread.cc:104
#42 0x00007432a6c7ccd7 in start_thread (arg=<optimized out>) at pthread_create.c:448
#43 0x00007432a6d00c8c in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78
(gdb) 
```
