### ISSUE TITLE
Segfault after filtering with invalid regex

### ISSUE THREAD

**Issue by tsipinakis** [newsboat/newsboat#501]
**Newsboat version**: 37cab69

Steps to reproduce the issue:

1. Enter any feed

2. Press F and input `title =~ "*A"`

3. Press the up or down key

**Other info you think is relevant**:

Backtrace:
```
#0  0x00007ffff77ae96f in __GI___regexec (preg=0x55555619ada0, string=0x55555618f2d0 "The Cloud Is Just Someone Else's Computer", nmatch=nmatch@entry=0, pmatch=pmatch@entry=0x0, eflags=eflags@entry=0) at regexec.c:213
#1  0x00005555557131c5 in newsboat::Matcher::matchop_rxeq (this=<optimized out>, e=0x55555618e030, item=0x555555c6ca20) at /usr/include/c++/8/bits/basic_string.h:2290
#2  0x0000555555714e59 in newsboat::Matcher::matches (this=this@entry=0x555555f383e8, item=0x555555c6ca20) at filter/FilterParser.h:37
#3  0x000055555563de8e in newsboat::ItemListFormAction::do_update_visible_items (this=0x555555f38330) at src/itemlistformaction.cpp:869
#4  0x000055555563e11a in newsboat::ItemListFormAction::prepare (this=0x555555f38330) at src/itemlistformaction.cpp:894
#5  0x00005555555f92bf in newsboat::View::run (this=<optimized out>) at /usr/include/c++/8/bits/shared_ptr_base.h:1018
#6  0x0000555555606a0a in newsboat::Controller::run (this=this@entry=0x7fffffffdeb0, args=...) at src/controller.cpp:467
#7  0x00005555555c8b25 in main (argc=1, argv=0x7fffffffe3f8) at newsboat.cpp:188
```

**Comment by Minoru** [comment]
Reproduced, thanks for the report! Will try to track it down now.
