### ISSUE TITLE
SIGSEGV on NixOS

### ISSUE THREAD

**Issue by lovesegfault** [newsboat/newsboat#713]
**Newsboat version (copy the output of `newsboat -v` or the first line of `git show`)**:
```
newsboat 2.18.0 - https://newsboat.org/
Copyright (C) 2006-2015 Andreas Krennmair
Copyright (C) 2015-2019 Alexander Batischev
Copyright (C) 2006-2017 Newsbeuter contributors
Copyright (C) 2017-2019 Newsboat contributors

Newsboat is free software licensed under the MIT License. (Type `newsboat -vv' to see the full text.)
It bundles JSON for Modern C++ library, licensed under the MIT License: https://github.com/nlohmann/json

newsboat 2.18.0
System: Linux 5.4.7 (x86_64)
Compiler: g++ 9.2.0
ncurses: ncurses 6.1.20190112 (compiled with 6.1)
libcurl: libcurl/7.67.0 OpenSSL/1.1.1d zlib/1.2.11 libssh2/1.9.0 nghttp2/1.40.0 (compiled with 7.67.0)
SQLite: 3.30.1 (compiled with 3.30.1)
libxml2: compiled with 2.9.10
```

Config file (copy from ~/.newsboat/config or ~/.config/newsboat/config):

```
max-items 0
browser /nix/store/fsn5b1hb4l07gr9xmdv7bcpjilixvdps-firefox-beta-bin-72.0b4/bin/firefox
reload-threads 12
auto-reload yes
reload-time 15
prepopulate-query-feeds yes

color background          color236   default
color listnormal          color248   default
color listnormal_unread   color6     default
color listfocus           color236   color12
color listfocus_unread    color15    color12
color info                color248   color236
color article             color248   default
highlight article "^(Feed|Link):.*$" color6 default bold
highlight article "^(Title|Date|Author):.*$" color6 default bold
highlight article "https?://[^ ]+" color10 default underline
highlight article "\\[[0-9]+\\]" color10 default bold
highlight article "\\[image\\ [0-9]+\\]" color10 default bold
highlight feedlist "^─.*$" color6 color236 bold
```

Steps to reproduce the issue:

1. Haven't been able to reproduce

**Other info you think is relevant**:
```
           PID: 10341 (newsboat)
           UID: 1000 (bemeurer)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Sat 2020-01-04 21:50:38 PST (1min 43s ago)
  Command Line: newsboat
    Executable: /nix/store/w9i28apzmw050kx5clhp5qyzlr2yfbdq-newsboat-2.18/bin/newsboat
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (bemeurer)
       Boot ID: a4394b141198490596e7f5e0d10e2a7f
    Machine ID: 7006856ef0c44432abe0db34d1884af0
      Hostname: foucault
       Storage: /var/lib/systemd/coredump/core.newsboat.1000.a4394b141198490596e7f5e0d10e2a7f.10341.1578203438000000000000.lz4
       Message: Process 10341 (newsboat) of user 1000 dumped core.
```

```
(gdb) bt full
#0  0x000000000057dcf8 in newsboat::RssFeed::update_items(std::vector<std::shared_ptr<newsboat::RssFeed>, std::allocator<std::shared_ptr<newsboat::RssFeed> > >) ()
No symbol table info available.
#1  0x000000000046a988 in newsboat::View::prepare_query_feed(std::shared_ptr<newsboat::RssFeed>) ()
No symbol table info available.
#2  0x0000000000565ddd in newsboat::Reloader::reload_all(bool) ()
No symbol table info available.
#3  0x0000000000486a27 in newsboat::DownloadThread::operator()() ()
No symbol table info available.
#4  0x00007f0b022ffb40 in ?? () from /nix/store/3cngcg3w6gvck6ngj60byx843f27pf76-gcc-9.2.0-lib/lib/libstdc++.so.6
No symbol table info available.
#5  0x00007f0b027bfef7 in start_thread () from /nix/store/4zhy7p7dhfjbaac0i0kb6f2ky1w3747k-glibc-2.27/lib/libpthread.so.0
No symbol table info available.
#6  0x00007f0b01db822f in clone () from /nix/store/4zhy7p7dhfjbaac0i0kb6f2ky1w3747k-glibc-2.27/lib/libc.so.6
No symbol table info available.
```

**Comment by Minoru** [comment]
Thanks for the report! No idea what exactly went wrong. Memory corruption during feed update?

I'll have to wait to see if more people run into this, perhaps that'll give us more info.

**Comment by lovesegfault** [comment]
Yeah I haven't been able to reproduce it either, it happened while opening a feed with new items in it. I figured I'd open an issue just to keep a record of it :)
